# Generated by Django 3.2 on 2022-09-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='context_key',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
