# Generated by Django 3.2 on 2022-09-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verificationcode_context_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='use_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
