# Generated by Django 3.2 on 2022-09-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('nickname', models.CharField(max_length=255, verbose_name='닉네임')),
                ('phone', models.CharField(max_length=255, verbose_name='전화번호')),
                ('email', models.CharField(max_length=255, verbose_name='이메일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
