# Generated by Django 3.2 on 2022-09-15 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='엑세스 토큰')),
                ('refresh_token', models.CharField(max_length=255, verbose_name='리프레시 토큰')),
                ('expires_at', models.DateTimeField(verbose_name='만료일시')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_key', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('phone', models.CharField(max_length=255, verbose_name='전화번호')),
                ('code', models.CharField(max_length=255, verbose_name='이메일')),
                ('verifies_at', models.DateTimeField(verbose_name='인증일시')),
                ('expires_at', models.DateTimeField(verbose_name='만료일시')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AddField(
            model_name='account',
            name='access_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accesstoken'),
        ),
        migrations.AddField(
            model_name='account',
            name='credential',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.credential'),
        ),
    ]
